print("本程序由御风工作室编写。")
a=int(input())
b=int(input())
print(str(a)+" "+"+"+" "+str(b)+" "+"="+" "+str(a+b))
print(str(a)+" "+"-"+" "+str(b)+" "+"="+" "+str(a-b))
print(str(a)+" "+"*"+" "+str(b)+" "+"="+" "+str(a*b))
print(str(a)+" "+"/"+" "+str(b)+" "+"="+" "+str(a/b))