s = 'Hello,Python!'
print("字符串\""+ s + "\"的长度为："+str(len(s)))
print("正向索引:")
print("第0个元素:"+s[0])
print("第2个元素:"+s[2])
print("第10个元素:"+s[10])
print("反向索引:")
print("最后一个元素:"+s[-1])
print("倒数第二个元素:"+s[-2])
print("倒数第五个元素:"+s[-5])
